exclude:
- /Animations/.*
- /Minecraft/.*
- /lib/.*
- /LYNGK/MySceneGraph.js
- /LYNGK/Primitives/Triangle.js
- /LYNGK/Animations/CircularAnimation.js
component_depth: 2
languages:
- python
- javascript